### PR TITLE
feat: Support optional cloudsql-proxy sidecar

### LINKED ISSUE #126: Support optional CloudSQL proxy sidecar
### Describe the feature request

I want unleash to optionally support cloudsql proxy sidecar as an alternative to postgres.

### Background

At the moment we are using externally deployed cloudsql proxy hooked up to unleash but sometime, transient network issues prevent DNS resolution between unleash pod and gcloudsql proxy service, having it run as a sidecar is more secure and the recommended way of deploying cloudsql proxy which also prevents the service from being advertised in the namespace.

### Solution suggestions

_No response_

### PR DESCRIPTION
**Pull request by brtknr**
## About the changes

Closes #126

### CODE REVIEW

**Comment by brtknr** [comment]
cc @chriswk @gastonfournier

**Review by chriswk — APPROVED** [review]
Thank you for the PR. Great that you assured that the sidecar is 100% optional. I'm going to merge this.

**Comment by iamdmitrij** [comment]
Hi, I'm having deployment issues with new version `3.0.11` of this chart. I've traced back the problem to this PR in [charts/unleash/templates/deployment.yaml#L67.](https://github.com/Unleash/helm-charts/blob/3bbf47e512757587493db86dc9cf8b168cbfc118/charts/unleash/templates/deployment.yaml#L67C5-L67C5)

As far as I understand deployment of chart will fail if you use extra secrets in value file.

```
unleash:
  secrets:
    AUTH_TENANT_ID: test
```

Some logs:
```
Error: UPGRADE FAILED: template: unleash/charts/unleash/templates/deployment.yaml:67:27: executing "unleash/charts/unleash/templates/deployment.yaml" at <include "unleash.fullname" .>: error calling include: template: unleash/charts/unleash/templates/_helpers.tpl:14:14: executing "unleash.fullname" at <.Values.fullnameOverride>: can't evaluate field Values in type string
##[error]Error: UPGRADE FAILED: template: unleash/charts/unleash/templates/deployment.yaml:67:27: executing "unleash/charts/unleash/templates/deployment.yaml" at <include "unleash.fullname" .>: error calling include: template: unleash/charts/unleash/templates/_helpers.tpl:14:14: executing "unleash.fullname" at <.Values.fullnameOverride>: can't evaluate field Values in type string
```

**Comment by brtknr** [comment]
This PR publishes version `3.1.0`, not `3.0.11`

**Comment by iamdmitrij** [comment]
Sorry, my bad. I'm using the newest version of this chart - `3.1.1`.

**Comment by brtknr** [comment]
Sorry about that, this should fix it: https://github.com/Unleash/helm-charts/pull/127/files

**Pull request merged**
