### PR TITLE
feat: add pod-disruption-budget support

### PR DESCRIPTION
**Pull request by jmsantorum**
## About the changes

Add support for PodDisruptionBudget

### CODE REVIEW

**Comment by sighphyre** [comment]
Hey @jmsantorum, thanks for tackling this!

I think we need to look this one over a bit and rope in some more eyes before we approve this

**Review by chriswk — APPROVED** [review]
Thank you for this contribution. I've given you an approval here, but I believe you'll need to bump your chart versions to get past our linting due to us being slow to pick up on this one, and us having released at least Unleash once since you made your PR.

**Comment by jmsantorum** [comment]
> Thank you for this contribution. I've given you an approval here, but I believe you'll need to bump your chart versions to get past our linting due to us being slow to pick up on this one, and us having released at least Unleash once since you made your PR.

sure! I'll do asap

**Comment by jmsantorum** [comment]
> Thank you for this contribution. I've given you an approval here, but I believe you'll need to bump your chart versions to get past our linting due to us being slow to pick up on this one, and us having released at least Unleash once since you made your PR.

should be done!

**Comment by chriswk** [comment]
Great. Merging then :)

**Pull request merged**
