### PR TITLE
allow ssl configuration

### PR DESCRIPTION
**Pull request by tylerbrewer2**
## About the changes
SSL configuration is not able to be passed via environment variable in the helm chart. Any attempt to pass stringified JSON ([docs](https://docs.getunleash.io/reference/deploy/configuring-unleash#dbssl-vs-database_ssl-options)) results in a Helm parsing error.

Semi related to #94

### CODE REVIEW

**Comment by chriswk** [comment]
Hi @tylerbrewer2 - Sorry for the late response. I even see we managed to get some other changes so your version is out of date, could I bother you to rebase on top of main, making sure to bump the chart version to one patch version new than what's currently on main. I'm inclined to accept this, it definitely looks to do what we want with stringifying and converting the yaml to json, but I want to make sure our CI linting and installing passes so I don't have to fix it on main after merging.

**Comment by tylerbrewer2** [comment]
No problem! Should be good now

**Review by chriswk — APPROVED** [review]
Thanks @tylerbrewer2 for your contribution . I'm :+1: on this. You will fail to lint though since you haven't bumped the Chart version. Could I bother you do so, and since you're already bumping the appVersion, maybe bump that to the most recent patch of 5.6.6

**Comment by nunogois** [comment]
I believe this fixes https://github.com/Unleash/helm-charts/issues/102

**Comment by tylerbrewer2** [comment]
@chriswk Sorry for dropping the ball on this but glad to see it merged in!

**Pull request closed without merging**
