### PR TITLE
Configure ssl for database connection

### LINKED ISSUE #14: DB connections fails for version 4.0.0
**Issue:**
With image tag 4.0.0, unleash server fails to start with following error.

`Failed to migrate db OperationalError: The server does not support SSL connections`

**Reason:**

postgres is not accepting ssl connection, but unleash trying to open db connection with SSL.

**Solution:**
Configure unleash to open DB connection with SSL disabled

### PR DESCRIPTION
**Pull request by prabhu43**
Signed-off-by: Prabhu Jayakumar <j.prabhu91@gmail.com>

Fixes #14

### CODE REVIEW

**Comment by ivarconr** [comment]
Thanks. Looks like a good improvement!

**Comment by ivarconr** [comment]
Could you also bump the chart version from 1.1.0 to 1.1.1?

**Comment by prabhutw** [comment]
@ivarconr Bumped the chart version to 1.1.1.

**Comment by prabhu43** [comment]
Hi @ivarconr 
Bumped the chart version to 1.1.1

**Pull request merged**
