### PR TITLE
add unleash-proxy helm chart

### PR DESCRIPTION
**Pull request by nkz-soft**
## About the changes
Well, i didn't find any chart for unleash proxy, but i need it for my frontend, so I did it 

### Important files
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml

### CODE REVIEW

**Review by chriswk — APPROVED** [review]
Hi nkz-soft.
Thank you for taking the time to make this. Going to approve and merge it. Great job.

**Comment by chriswk** [comment]
I see our lints balks at missing maintainers, would you be willing to add your username here before we merge? Alternately, you can add mine (chriswk) if you'd prefer to not end up maintaining this.

**Comment by nkz-soft** [comment]
@chriswk  I have added myself. I would love to participate in the project.

**Comment by chriswk** [comment]
Thank you so much for this @nkz-soft . Great job.

**Pull request merged**
