### PR TITLE
Added support for initContainers

### PR DESCRIPTION
**Pull request by plavy**
`deployment.yaml` supports initContainers

### CODE REVIEW

**Comment by ivarconr** [comment]
Will this work for you  @lbenc135?

**Review by ivarconr — APPROVED** [review]
lgtm ;)

**Review by FredrikOseberg — APPROVED** [review]
LGTM

**Comment by lbenc135** [comment]
> Will this work for you @lbenc135?

Looks good :+1:

**Comment by evanstucker-hates-2fa** [comment]
Looks good to me as well. Not sure why it's failing on the super-linter...

**Comment by plavy** [comment]
> Looks good to me as well. Not sure why it's failing on the super-linter...

It looks like there is a bug in the linter?

**Comment by ivarconr** [comment]
I think the linter fails because this is an external PR. Merging now!

**Pull request merged**
