### PR TITLE
https://github.com/Unleash/helm-charts/issues/113: Support for pod la…

### LINKED ISSUE #113: Unleash Edge helm chart should allow podLabels to be specified a la Unleash
### Describe the feature request

I would like to be able to specify pod labels in the Unleash Edge helm chart. 

### Background

We use Istio and the lack of ability to specify those labels in Edge prevents us from injecting the Istio sidecar (via code in  values.yaml). This results in us losing a bit of observability in terms of the request metrics we get from Istio.

### Solution suggestions

I'd like to simply copy the relevant content from the Unleash helm chart and apply it to the Unleash Edge helm chart.

### PR DESCRIPTION
**Pull request by YayBurritos**
## About the changes

Added support for pod labels in the Unleash Edge deployment resource

Closes #113

### CODE REVIEW

**Comment by YayBurritos** [comment]
> In order to pass our lints, could you please bump the patch version in the Chart.

Done! Thanks for the reminder!

**Comment by YayBurritos** [comment]
@chriswk : What's the next step here? Need anything additional from me? Thanks!

**Review by gardleopard — APPROVED** [review]
LGTM

**Comment by FredrikOseberg** [comment]
@YayBurritos We've merged this now and released a new chart, you should be able to use it now. Thanks for contributing!

**Pull request merged**
