### PR TITLE
Allow topologySpreadConstraints for unleash

### PR DESCRIPTION
**Pull request by pvickery-ParamountCommerce**
## About the changes

Adds support for topologySpreadConstraints to the unleash chart. This was copied [from the unleash-edge helm chart
](https://github.com/search?q=repo%3AUnleash%2Fhelm-charts+topologySpreadConstraints+path%3A%2F%5Echarts%5C%2Funleash-edge%5C%2F%2F&type=code)

### CODE REVIEW

**Comment by chriswk** [comment]
Hi @pvickery-ParamountCommerce - Thanks for your contribution. It's going to fail our checks, could I trouble you to bump the patch version inside Chart.yaml by one, so that I can merge and release this?

**Review by chriswk — CHANGES_REQUESTED** [review]
Hi!

Thanks so much for your contribution.

We need a patch bump inside `Chart.yaml` to successfully pass our tests; once that's in place I'll approve and merge this

**Comment by pvickery-ParamountCommerce** [comment]
> Hi!
> 
> Thanks so much for your contribution.
> 
> We need a patch bump inside `Chart.yaml` to successfully pass our tests; once that's in place I'll approve and merge this

Thanks! I've bumped the version and applied the change to unleash-proxy as well. I also reset and squashed my changes for a cleaner commit history

**Review by chriswk — APPROVED** [review]

**Comment by chriswk** [comment]
again, thank you, sorry for the late response. This got away from me. Will merge today

**Comment by pvickery-ParamountCommerce** [comment]
> again, thank you, sorry for the late response. This got away from me. Will merge today

Thanks Chris! and no worries :slightly_smiling_face:

**Pull request merged**
