### PR TITLE
feat(unleash-proxy): add more var env entries

### PR DESCRIPTION
**Pull request by zied-jt**
## About the changes

This PR introduce some env var available in [unleash proxy configuration](https://docs.getunleash.io/sdks/unleash-proxy#configuration)

### Important files

- `charts/unleash-proxy/templates/deployment.yaml`
- `charts/unleash-proxy/values.yaml`

### CODE REVIEW

**Review by nkz-soft — APPROVED** [review]

**Comment by zied-jt** [comment]
Thanks @nkz-soft for reviewing. 

@chriswk any chance to get a review for this PR and #55 ? Thanks !

**Comment by OmbraDiFenice** [comment]
+1 

Also it would be nice to add a variable to set the UNLEASH_INSTANCE_ID environment too, since it's required to use the proxy with GitLab as far as I understand

**Review by chriswk — APPROVED** [review]
LGTM

**Comment by zied-jt** [comment]
@chriswk Thanks for reviewing
@gastonfournier, @chriswk: PR is rebased and CI is fixed (separate PR #63 if needed).

**Comment by zied-jt** [comment]
For `install-chart` failing checks, we need a server host as requirement

**Pull request merged**
