### PR TITLE
Update hpa.yaml use autoscaling/v2

### PR DESCRIPTION
**Pull request by yxxhero**
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126

## About the changes

Closes #

### CODE REVIEW

**Comment by yxxhero** [comment]
https://kubernetes.io/releases/patch-releases/#non-active-branch-history

**Comment by chriswk** [comment]
Hi @yxxhero . thank you for this contribution. Could I ask you to please bump the Chart version so that our auto-tests actually work.

**Comment by yxxhero** [comment]
@chriswk 6.7.3? right? Thanks very much.

**Comment by yxxhero** [comment]
@chriswk fixed.

**Comment by chriswk** [comment]
Thank you. Running the linting now. I aim to have this merged today. Thank you again. :)

**Comment by yxxhero** [comment]
@chriswk  all is ok. by the way. when will the new version be released? thanks very much.

**Review by chriswk — APPROVED** [review]
Nice. Thanks. This will cause us to move minimum supported k8s version to 1.23.0.

**Comment by yxxhero** [comment]
@chriswk please rerun the ci jobs.

**Review by chriswk — CHANGES_REQUESTED** [review]
I'm sorry, but this won't validate against the "autoscaling/v2" schema. So I couldn't merge it yesterday. I found that our repository doesn't actually run validation with autoscaling and ingresses turned on, so didn't figure out that it broke until I actually tried to install the helm chart on a 1.25 cluster. I am updating our validation to validate all schemas (so turn on all features). By default autoscaling is disabled, so that's why it passed the lints.

We still appreciate this PR, and will use it as a template when upgrading our schemas to support v1.23-v1.26 range.

**Pull request closed without merging**
